abpoll/blueprints/post/views.py
from flask import (
    render_template,
    redirect,
    url_for,
    flash,
    request,
    abort,
    Blueprint,
)
from flask_login import current_user

from lib.upload_files import allowed_image_file, random_image_background
from lib.util_json import parse_arg_from_requests
from lib.util_json import render_json
from lib.util_post import (
    random_post_id,
    return_cv2_image,
    create_array_from_argument,
    save_image_to_server,
    vertical_attach_images
)

from abpoll.extensions import db
from abpoll.blueprints.post.models import Post, PostViewed
from abpoll.blueprints.general.models.activity import Notifications
from abpoll.blueprints.user.models import User
from lib.upload_files import delete_image_from_cloudflare
from sqlalchemy.sql.expression import func, and_

from config.settings import RECOMMEND_NUMBER

post = Blueprint("post", __name__, template_folder="templates")


@post.route("/u/<username>")
def user_page(username):
    username = username.lower()
    user_object = (db.session.query(User).filter(User.username == username).first())
    if user_object is not None:
        posts = db.session.query(Post).filter(and_(Post.author_id == user_object.id, Post.voting_open)).order_by(
            Post.created_on.desc()).all()

        return render_template("post/profile.html",
                               User=user_object,
                               posts=posts,
                               )
    else:
        abort(404)


@post.route("/u/<username>/votes")
def user_page_votes(username):
    username = username.lower()
    user_object = (db.session.query(User).filter(User.username == username).first())
    if user_object is not None:
        posts = db.session.query(PostViewed).filter(PostViewed.author_id == user_object.id).order_by(
            PostViewed.created_on.desc()).all()
        posts = [x.post for x in posts]

        return render_template("post/profile-votes.html", User=user_object, posts=posts)
    else:
        abort(404)


# TODO: ADD Ask me anything tab

@post.route("/edit_user_page", methods=["POST"])
def edit_user_page():
    if not current_user.is_active:
        return redirect(
            f"{url_for('user.login')}?next=%2fmy-account%2fsettings"
        )

    selected_user = User.query.get(current_user.id)
    if selected_user is None:
        return abort(404)
    selected_user.description = request.values.get("description")
    location = request.values.get("location")
    selected_user.location = None

    if location != "" or location is None:
        selected_user.location = location

    if "background" not in request.files:
        # No file part
        pass
    else:
        file = request.files["background"]
        if file.filename == "":
            pass
        elif file and allowed_image_file(file.filename):
            from abpoll.blueprints.post.tasks import change_all_default_posts_background
            new_background = save_image_to_server(file)
            # If selected user already changed their background
            if selected_user.back_ground is not None and selected_user.back_ground != "/images/account/bg.png":
                delete_image_from_cloudflare(selected_user.back_ground)
                change_all_default_posts_background(selected_user.id, new_background, selected_user.back_ground)
            #  if selected user didn't change their background
            else:
                change_all_default_posts_background(selected_user.id, new_background)

            selected_user.back_ground = new_background

        else:
            #       file is not supported.
            #       You can only upload .png, .jpg, .jpeg, .gif files
            pass

    social_1_option = request.values.get("social_1_option")
    social_1_handle = request.values.get("social_1")

    if len(social_1_handle) <= 1:
        selected_user.social_1_handle = None
        selected_user.social_1_link = "#"
    else:
        if social_1_option == "Twitter":
            social_1 = social_1_handle.replace("@", "")
            social_1_link = f"https://twitter.com/{social_1}"
            selected_user.social_1_option = "twitter"
            selected_user.social_1_link = social_1_link
            selected_user.social_1_handle = social_1
        if social_1_option == "Instagram":
            social_1 = social_1_handle.replace("@", "")
            social_1_link = f"https://instagram.com/{social_1}"
            selected_user.social_1_option = "instagram"
            selected_user.social_1_link = social_1_link
            selected_user.social_1_handle = social_1
        if social_1_option == "Twitch":
            social_1 = social_1_handle.replace("@", "")
            social_1_link = f"https://twitch.tv/{social_1}"
            selected_user.social_1_option = "twitch"
            selected_user.social_1_link = social_1_link
            selected_user.social_1_handle = social_1
        if social_1_option == "Youtube":
            selected_user.social_1_option = "youtube"
            selected_user.social_1_link = social_1_handle
            selected_user.social_1_handle = "My Youtube"
        if social_1_option == "Website":
            web_link = f'https://{((social_1_handle.replace("www.", "")).replace("https://", "")).replace("http://", "")}'
            selected_user.social_1_option = "globe"
            selected_user.social_1_link = web_link
            selected_user.social_1_handle = "My Website"

    social_2_option = request.values.get("social_2_option")
    social_2_handle = request.values.get("social_2")

    if len(social_2_handle) <= 1:
        selected_user.social_2_handle = None
        selected_user.social_2_link = "#"
    else:
        if social_2_option == "Twitter":
            social_2 = social_1_handle.replace("@", "")
            social_2_link = f"https://twitter.com/{social_2}"
            selected_user.social_2_option = "twitter"
            selected_user.social_2_link = social_2_link
            selected_user.social_2_handle = social_2
        if social_2_option == "Instagram":
            social_2 = social_2_handle.replace("@", "")
            social_2_link = f"https://instagram.com/{social_2}"
            selected_user.social_2_option = "instagram"
            selected_user.social_2_link = social_2_link
            selected_user.social_2_handle = social_2
        if social_2_option == "Twitch":
            social_2 = social_2_handle.replace("@", "")
            social_2_link = f"https://twitch.tv/{social_2}"
            selected_user.social_2_option = "twitch"
            selected_user.social_2_link = social_2_link
            selected_user.social_2_handle = social_2
        if social_2_option == "Youtube":
            selected_user.social_2_option = "youtube"
            selected_user.social_2_link = social_2_handle
            selected_user.social_2_handle = "My Youtube"
        if social_2_option == "Website":
            selected_user.social_2_option = "globe"
            selected_user.social_2_link = social_2_handle
            selected_user.social_2_handle = "My Website"

    selected_user.save()
    return redirect(f"/u/{current_user.username}")


@post.route("/p/<post_id>", methods=["GET", "POST"])
def post_page(post_id):
    posts = Post.query.get(post_id)
    if posts is not None:
        return render_template("post/view-post.html", post=posts)
    abort(404)


@post.route("/delete-post", methods=["POST"])
def delete_post_id():
    post_id = parse_arg_from_requests("post_id")
    if post_id is not None:

        if not current_user.is_active:
            return render_json(301, f"{url_for('user.login')}?next=%2fp%2f{post_id}")

        post_to_delete = Post.query.get(post_id)
        username = post_to_delete.author.username
        if post_to_delete is not None:
            if current_user == post_to_delete.author or current_user.role == 'admin':
                from abpoll.blueprints.post.tasks import delete_post_id
                delete_post_id(post_id)
                return render_json(301, url_for('post.user_page', username=username))

    return abort(404)

abpoll/blueprints/post/templates/post/profile-sorted.html
{% extends 'layouts/user-page.html' %}
{% import 'macros/sort.html' as post_sort %}
{% block post_content %}

{% if current_user.is_active and User == current_user%}
<!-- Start Navigation -->
<div class="row justify-content-center text-center mt-3">
    <div class="col-6 border-top pt-3">
        <a href="javascript:void(0)" class="text-dark" title="Posts"><span class="mb-0 d-inline-block me-1"><i class="uil uil-images"></i></span> Posts</a>
    </div>
    <div class="col-6 pt-3">
        <a href="{{url_for('post.user_page_votes', username=User.username)}}" class="text-muted" title="Votes"><span class="mb-0 d-inline-block me-1"><i class="uil uil-graph-bar"></i></span> Votes</a>
    </div>
</div><!--end row-->
{% endif %}

<div class="row justify-content-center mt-4">
    {{ post_sort.render_sort(fingerprints, posts, User) }}
</div>
<!-- End Posts -->

{% if posts | length > 1 %}
<!-- sort votes -->
<div class="row gy-3 bg-soft-primary border-0 mx-0 rounded pb-4 mb-4" style="border: 0 !important;">
    <h5 class="mb-0 hstack">Sort the answers <span class="ms-auto alert alert-warning py-1 m-0">Beta</span></h5>
    <p class="text-dark">Sort the polls by question and answers, then see if you can recognise some patterns.</p>
    <input name="poll_id" type="text" hidden>

    <div class="col-12">
        <input name="question-select" class="form-control border-0" placeholder="question" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" required="">
        <div class="invalid-feedback">
            Questions is required
        </div>
    </div>

    <div class="col-12">
        <input type="text" name="answer-select" class="form-control border-0" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" disabled="" placeholder="answer" required="">
        <div class="invalid-feedback">
            Answer is required
        </div>
    </div>

    <div class="col-12">
        <input type="submit" name="submit-sort" value="Sort" class="form-control border-0 btn" disabled="" placeholder="answer">
    </div>
</div>
<script src="/js/sort.js"></script>
{% endif %}

<script src="/js/abpoll.js"></script>
<script>
    window.onload = function() {
        load_right_sidebar();
    };
</script>
{% endblock %}

abpoll/blueprints/post/templates/post/profile-votes.html
{% extends 'layouts/user-page.html' %}
{% block post_content %}
<!-- Start Navigation -->
{% if current_user.is_active and User == current_user%}
<!-- Start Navigation -->
<div class="row justify-content-center text-center mt-3">
    <div class="col-6 pt-3">
        <a href="{{url_for('post.user_page', username=User.username)}}" class="text-muted" title="Posts"><span class="mb-0 d-inline-block me-1"><i class="uil uil-images"></i></span> Posts</a>
    </div>
    <div class="col-6 border-top pt-3">
        <a href="javascript:void(0)" class="text-dark" title="Votes"><span class="mb-0 d-inline-block me-1"><i class="uil uil-graph-bar"></i></span> Votes</a>
    </div>
</div><!--end row-->
{% endif %}

<div class="row justify-content-center mt-4">
    {% for post in posts %}
        <div class="col-12 spacing picture-item">
            <div class="card border-0 work-container position-relative d-block overflow-hidden rounded rounded-0">
                <div class="card-body p-0">
                    <a href="{{url_for('post.post_page', post_id=post.id)}}">
                        <img src="{{post.serve_portrait_image()}}" class="img-fluid w-100" alt="work-image">
                    </a>
                    <!-- voting mechanism -->
                    {% if post.post_format == 'Trivia' %}
                        <div class="center-interactive {% if post.image_2 != None %}top-50{% else %}top-75{% endif %} i-amphtml-element i-amphtml-layout-container i-amphtml-story-interactive-component i-amphtml-built i-amphtml-layout ">
                            <h1 class="amp-poll-title w-100 text-center m-0 fst-normal fs-4 lh-sm fw-bolder">{{post.title}}</h1>
                            {% if post.did_user_vote(user_id=User.id) %}
                                <!-- Removed id bellow -->
                                <div class="i-amphtml-story-interactive-quiz-container i-amphtml-story-interactive-post-selection i-amphtml-story-interactive-container i-amphtml-story-interactive-has-data">
                                    <div class="i-amphtml-story-interactive-quiz-option-container">
                                        {% for option in post.options %}
                                        <button data-current="{{post.options_vote[loop.index0]}}" data-option="{{ letters[loop.index0] }}" style="--option-percentage:{{post.percentage(post.options_vote[loop.index0])}}%;" {% if loop.index0 == post.selected_option %}correct="correct"{% endif %} class="i-amphtml-story-interactive-quiz-option i-amphtml-story-interactive-option {% if post.voted_index(user_id=User.id) == loop.index0 %}i-amphtml-story-interactive-option-selected{% endif %} "><span class="i-amphtml-story-interactive-quiz-answer-choice">{{ letters[loop.index0] | upper}}</span><span class="i-amphtml-story-interactive-quiz-option-text">{{option | safe }}</span><span class="i-amphtml-story-interactive-quiz-percentage-text">{{post.percentage(post.options_vote[loop.index0])}}%</span></button>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% else %}
                                <!-- Removed id bellow -->
                                <div class="i-amphtml-story-interactive-quiz-container i-amphtml-story-interactive-container i-amphtml-story-interactive-has-data">
                                    <div class="i-amphtml-story-interactive-quiz-option-container">
                                        {% for option in post.options %}
                                        <button data-current="{{post.options_vote[loop.index0]}}" data-option="{{ letters[loop.index0] }}" {% if loop.index0 == post.selected_option %}correct="correct"{% endif %} class="i-amphtml-story-interactive-quiz-option i-amphtml-story-interactive-option"><span class="i-amphtml-story-interactive-quiz-answer-choice">{{ letters[loop.index0] | upper}}</span><span class="i-amphtml-story-interactive-quiz-option-text">{{option | safe }}</span><span class="i-amphtml-story-interactive-quiz-percentage-text"></span></button>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    {% else %}
                        {% if post.did_user_vote(user_id=User.id) %}
                        <div class="position-absolute {% if post.image_2 == None %}top-75{% else %}top-50{% endif %} start-50 translate-middle w-60">
                            <h1 class="amp-poll-title w-100 text-center m-0 fst-normal fs-4 lh-sm fw-bolder">{{post.title}}</h1>
                            <!-- Removed id bellow -->
                            <div class="i-amphtml-story-poll-quad blue-dark i-amphtml-story-poll-responded" data-total="1">
                                <span style="--percentage:{{post.percentage(post.options_vote[0])}}%;" class="i-amphtml-story-poll-option bg-light mt-2 btn btn-pills btn-vote border-0 {% if post.voted_index(user_id=User.id) == 0 %}i-amphtml-story-poll-option-selected {% endif %}" data-current="{{post.options_vote[0]}}" data-option="a">
                                    <span class="i-amphtml-story-poll-option-title text-truncate">{{post.a_text}}</span>
                                    <span class="i-amphtml-story-poll-option-percentage">{{post.percentage(post.options_vote[0])}}%</span>
                                </span>
                                <span style="--percentage:{{post.percentage(post.options_vote[1])}}%;" class="i-amphtml-story-poll-option bg-light mt-2 btn btn-pills btn-vote border-0 {% if post.voted_index(user_id=User.id) == 1 %}i-amphtml-story-poll-option-selected {% endif %}" data-current="{{post.options_vote[1]}}" data-option="b">
                                    <span class="i-amphtml-story-poll-option-title text-truncate">{{post.b_text}}</span>
                                    <span class="i-amphtml-story-poll-option-percentage">{{post.percentage(post.options_vote[1])}}%</span>
                                </span>
                            </div>
                        </div>
                        {% else %}
                        <div class="position-absolute {% if post.image_2 == None %}top-75{% else %}top-50{% endif %} w-60 start-50 translate-middle">
                            <h1 class="amp-poll-title w-100 text-center m-0 fst-normal fs-4 lh-sm fw-bolder">{{post.title}}</h1>
                            <!-- Removed id bellow -->
                            <div class="i-amphtml-story-poll-quad blue-dark" data-total="{{post.options_vote[0] + post.options_vote[1]}}">
                                <span style="--percentage:50%" class="i-amphtml-story-poll-option bg-light mt-2 btn btn-pills btn-vote border-0" data-current="{{post.options_vote[0]}}" data-option="a">
                                    <span class="i-amphtml-story-poll-option-title text-truncate">{{post.a_text}}</span>
                                    <span class="i-amphtml-story-poll-option-percentage"></span>
                                </span>
                                <span style="--percentage:50%" class="i-amphtml-story-poll-option bg-light mt-2 btn btn-pills btn-vote border-0" data-current="{{post.options_vote[1]}}" data-option="b">
                                    <span class="i-amphtml-story-poll-option-title text-truncate">{{post.b_text}}</span>
                                    <span class="i-amphtml-story-poll-option-percentage"></span>
                                </span>
                            </div>
                        </div>
                        {% endif %}
                    {% endif %}
                    <!-- end Voting mechanism -->
                </div>
            </div>
            <div class="post-meta d-flex justify-content-between text-muted p-2">
                <ul class="list-unstyled mb-0">
                    <li class="list-inline-item me-2 mb-0">
                        <i class="uil uil-user"></i> <a href="/u/{{post.author.username}}"><span class="author text-muted">{{post.author.display_username()}}</span></a>
                    </li>
                    <li class="list-inline-item me-2 mb-0">
                        <i class="uil uil-check-circle"></i> <span class="total-votes">{{post.options_vote[0] + post.options_vote[1]}}</span>
                    </li>
                    <li class="list-inline-item">
                        <a href="javascript:postGetComments('{{post.id}}', 1)" class="text-muted comments">
                            <i class="uil uil-comment"></i> <span id="{{post.id}}-number" class="total-comments">{{post.post_comments | length}}</span>
                        </a>
                    </li>
                </ul>
                <a onclick='triggerShare({{url_for('post.post_page', post_id=post.id, _external=True) | tojson}}, {{post.title | tojson }}, "")' class="text-muted cursor-pointer"><i class="uil uil-share-alt"></i></a>
            </div>        
        </div><!--end col-->
    {% endfor %}
</div>
<!-- End Posts -->
{% endblock %}
{% block footer %}
<script src="/js/abpoll.js"></script>
<!-- shuffle js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Shuffle/5.4.1/shuffle.min.js" integrity="sha512-26vtWkj1Yt/eY2Ykb7TO/RzzysOKS7zaD/055jS+2IW4DX89qlH/HziTFqfzMLAxpFVpYhPWgTdCcavzf8Qs8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

abpoll/blueprints/post/templates/post/profile.html
{% import 'macros/post.html' as post_template %}
{% extends 'layouts/user-page.html' %}
{% block post_content %}
{% if current_user.is_active and User == current_user%}
<!-- Start Navigation -->
<div class="row justify-content-center text-center mt-3">
    <div class="col-6 border-top pt-3">
        <a href="javascript:void(0)" class="text-dark" title="Posts"><span class="mb-0 d-inline-block me-1"><i class="uil uil-images"></i></span> Posts</a>
    </div>
    <div class="col-6 pt-3">
        <a href="{{url_for('post.user_page_votes', username=User.username)}}" class="text-muted" title="Votes"><span class="mb-0 d-inline-block me-1"><i class="uil uil-graph-bar"></i></span> Votes</a>
    </div>
</div><!--end row-->
{% endif %}

<div class="row justify-content-center mt-4">
    {% for post in posts %}
    {{post_template.card(post)}}
    {% endfor %}
</div>
<!-- End Posts -->

<script src="/js/abpoll.js"></script>
<script>
    window.onload = function() {
        load_right_sidebar();
    };
</script>
{% endblock %}