abpoll/blueprints/groups/views.py
from flask import Blueprint, abort, flash, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required
from sqlalchemy import or_
from sqlalchemy.exc import IntegrityError

from abpoll.blueprints.groups.models import Group, GroupParticipant
from abpoll.blueprints.post.models import Post, PostViewed
from abpoll.extensions import db
from lib.upload_files import delete_image_from_cloudflare
from lib.util_json import parse_arg_from_requests, render_json
from lib.util_post import save_image_to_server
from lib.util_sqlalchemy import generate_random_id

groups = Blueprint("groups", __name__, template_folder="templates")


@groups.route("/groups")
def index():
    """ Show the groups and show the create groups button and search """
    all_groups = Group.get_user_groups()
    return render_template("groups/index.html", groups=all_groups)


@groups.route("/groups/<int:group_id>")
def view(group_id):
    """ Show the groups and show the create groups button and search """
    group = Group.query.get(group_id)
    if group:
        if group not in Group.get_user_groups():
            flash("You need to join the group to view it", "warning")
            return redirect(url_for('groups.index') + f"?join={group_id}")
        return render_template("groups/view.html", group=group)
    else:
        return abort(404)


@groups.route("/groups/<int:group_id>/<int:page>")
def retrieve_posts(group_id, page):
    """ render the posts the group voted on"""
    group = Group.query.get(group_id)
    if group:
        if group not in Group.get_user_groups():
            flash("You need to join the group to view it", "warning")
            return render_json(301, url_for("groups.index"))

        group_participants = GroupParticipant.query.filter_by(group_id=group_id).all()

        group_logged_in_participants_ids = []
        group_guest_participants_ids = []
        for participant in group_participants:
            if participant.user_id is not None:
                group_logged_in_participants_ids.append(participant.user_id)
            else:
                group_guest_participants_ids.append(participant.fingerprint_id)

        posts = Post.query.join(PostViewed).filter(
            or_(PostViewed.author_id.in_(group_logged_in_participants_ids),
                PostViewed.fingerprint_id.in_(group_guest_participants_ids))).order_by(
            PostViewed.id.desc()).paginate(page=page, per_page=10)

        serialized_posts = []

        for post in posts.items:
            output = post.serialize
            output["options_vote"] = [0, 0, 0, 0]
            for post_viewed in post.post_viewed:
                if post_viewed.author_id in group_logged_in_participants_ids or \
                        post_viewed.fingerprint_id in group_guest_participants_ids:
                    output["options_vote"][post_viewed.user_vote_id] += 1
            output["total_votes"] = sum(output["options_vote"])
            serialized_posts.append(output)

        return render_json(200, serialized_posts)
    return render_json(404, "group not found")


@groups.route("/groups/create", methods=["POST"])
@login_required
def create():
    """ Show the groups and show the create groups button and search """

    # validate the form
    name = request.values.get("name")
    if name is None or len(name) < 3 or len(name) > 30:
        flash("Please enter a valid name 3-30 characters", "danger")
        return redirect(url_for('groups.index'))

    description = request.values.get("description")
    if description is None or len(description) == 0 or len(description) > 160:
        flash("Please enter a valid description 1-160 characters", "danger")
        return redirect(url_for('groups.index'))

    location = request.values.get("location", None)[:30]
    privacy = request.values.get("privacy")
    group_id = generate_random_id(Group, 7)

    # save the group
    new_group = Group(
        id=group_id,
        name=name,
        author_id=current_user.id,
        description=description,
        location=location,
        privacy=privacy,
    )
    new_group.save()

    new_participant = GroupParticipant(
        group_id=group_id,
        user_id=current_user.id
    )
    new_participant.save()
    flash("Group created successfully", "success")
    return redirect(url_for("groups.index"))


@groups.route("/groups/join", methods=["POST"])
def join():
    """ Join the group """
    group_id = parse_arg_from_requests("group_id", type=int)
    if group_id is None:
        return render_json(400, "Invalid format double check your Id")
    group = Group.query.get(group_id)
    if group:
        # check if this user is already a participant in this group
        try:
            if current_user.is_active:
                new_participant = GroupParticipant(
                    group_id=group_id,
                    user_id=current_user.id
                )
                new_participant.save()
            else:
                try:
                    if session["fingerprint_id"]:
                        new_participant = GroupParticipant(
                            group_id=group_id,
                            fingerprint_id=session["fingerprint_id"]
                        )
                        new_participant.save()
                except KeyError:
                    return render_json(400, "Unable to process request right now reload the page or try again later")

            flash("Successfully joined the group", "success")
            return render_json(200, url_for("groups.view", group_id=group_id))
        except IntegrityError:
            db.session.rollback()
            flash("You are already in the group", "info")
            return render_json(200, url_for("groups.view", group_id=group_id))
    else:
        return render_json(404, "This group does not exist")


@groups.route("/groups/edit", methods=["POST"])
@login_required
def edit():
    """ Show the groups and show the create groups button and search """
    group_id = request.values.get("group_id", type=int)
    if group_id is None:
        return abort(404)

    group_object = Group.query.get(group_id)
    if group_object is None:
        return abort(404)

    if group_object.author_id != current_user.id:
        return abort(404)

    name = request.values.get("name")
    if name is None or len(name) < 3 or len(name) > 30:
        flash("Please enter a valid name 3-30 characters", "danger")
        return redirect(url_for("groups.view", group_id=group_id))

    description = request.values.get("description")
    if description is None or len(description) == 0 or len(description) > 160:
        flash("Please enter a valid description 1-160 characters", "danger")
        return redirect(url_for("groups.view", group_id=group_id))

    location = request.values.get("location", None)[:30]
    privacy = request.values.get("privacy")

    group_object.name = name
    group_object.description = description
    group_object.location = location
    group_object.privacy = privacy
    group_object.save()

    background = request.files['background']

    if background is not None and background.filename != "":
        if group_object.background is not None:
            delete_image_from_cloudflare(group_object.background)
        group_object.background = save_image_to_server(background)
        group_object.save()

    flash("Successfully edited", "success")
    return redirect(url_for("groups.view", group_id=group_id))


@groups.route("/groups/delete", methods=["POST"])
@login_required
def delete():
    """ Delete the group if given the group id """
    group_id = request.values.get("group_id", type=int)
    if group_id is None:
        flash("An error occurred while processing the deletion", "warning")
        return redirect(url_for('groups.index'))

    group_object = Group.query.get(group_id)
    if group_object is None:
        flash("An error occurred while processing the deletion", "warning")
        return redirect(url_for('groups.index'))

    if group_object.author_id != current_user.id:
        flash("An error occurred while processing the deletion", "warning")
        return redirect(url_for('groups.index'))

    if group_object.background is not None:
        delete_image_from_cloudflare(group_object.background)

    group_object.delete()
    flash("Successfully deleted your group", "success")
    return redirect(url_for('groups.index'))

abpoll/blueprints/groups/templates/groups/index.html
{% import 'macros/items.html' as items %}
{% import 'macros/sidebar.html' as sidebar %}
{% extends 'layouts/base-2.html' %}
{% block title %}Groups / ABpoll{% endblock %}
{% block description %}Create groups and see what your group chooses.{% endblock %}
{% block featured_image %}https://imagedelivery.net/hnHx9kxJyligwC1X9CPssg/939d3f91-fa8b-4d78-fac6-4322c74b1b00/public{% endblock %}
{% block header %}
<meta name="keywords" content="online voting, polls, society, likes, groups." />
<meta name="revisit-after" content="1 days">
{%endblock %}
{% block content %}
<div class="mt-4 d-block d-md-none">
    <!-- Spacer -->
</div>
<!-- Start -->
<section class="section">
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-xl-5 col-lg-6 col-md-7 col-sm-12 order-md-2 order-lg-2 order-1">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{category}} fade show m-0 mb-4">{{ message|safe }}</div>
                {% endfor %}
                {% endif %}
                {% endwith %}
       
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h6 class="ps-1 m-0">Groups</h6>
                    <a data-bs-target="#CreateGroupForm" data-bs-toggle="modal" class="btn btn-icon btn-primary rounded-circle"><i class="uil uil-plus"></i></a>
                </div>        
                {% if groups | length == 0 %}
                <div class="bg-half-80 bg-light mb-4 rounded">
                    <h1 class="title d-flex text-primary justify-content-center"><i class="uil uil-layer-group-slash"></i></h1>
                    <h5 class="title d-flex justify-content-center">No Groups found</h5>
                    <p class="text-muted text-center">
                        {% if current_user.is_active %}
                        You are not yet in any groups but you can create one and share the code with friends
                        {% else %}
                        You are not yet in any groups but you can log in to create one
                        {% endif %}
                    </p>
                </div>
                {% else %}
                    {% for group in groups %}
                            <div class="cursor-pointer d-flex p-3 rounded bg-light border-0 my-4 justify-content-between">
                                <div class="col-4 d-flex align-items-start flex-column">
                                    <div class="mb-auto">
                                        <a href="{{url_for('groups.view', group_id=group.id)}}">
                                        <img src="{{group.background_index() or 'https://imagedelivery.net/hnHx9kxJyligwC1X9CPssg/2a3acbc2-d8af-4968-9417-4829c614f600/profile'}}" class="avatar avatar-group-md rounded border shadow" alt="{{group.name}}'s banner">
                                        </a>
                                    </div>
                                    <div class="w-100 text-center mt-2">
                                        <span onclick='triggerShare({{url_for('groups.view', group_id=group.id, _external=True) | tojson() }}, {{group.name | tojson }}, {{group.description | tojson }})' class="btn text-muted m-0 p-0" title="Share this group">
                                            <i class="uil uil-share-alt h5"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-8 ps-2 text-muted">
                                    <a href="{{url_for('groups.view', group_id=group.id)}}">
                                        <div class="d-flex justify-content-between align-items-center">
                                            <h5 class="mb-0 text-dark">{{group.name}}</h5>
                                            <span class="badge rounded-md bg-info p">{{group.number_of_participants()}}<i class="uil uil-user"></i></span>
                                        </div>
                                        <p class="text-muted mb-0">{{group.description}}</p>
                                        <p class="text-muted mt-2 mb-0 small">
                                            <span class="text-info me-2">Group Code:</span> {{group.clean_spaced_id() }}
                                        </p>
                                        {% if group.location %}
                                        <p class="text-muted mb-0 small">
                                            <span class="text-info me-2">Location: </span> {{group.location }}
                                        </p>
                                        {% endif %}
                                    </a>


                                </div>
                            </div>

                     {% endfor %}
                {% endif %}


            </div>

            {{ sidebar.users(class_to_add="", how_it_works="Create a group or join a group and see what your group has voted on. This is the best way to know more about each other. You can also try to guess who voted what.", active=current_user.is_active) }}


        </div>
    </div>
</section>


<!-- create group modal start -->
<div class="modal fade" id="CreateGroupForm" tabindex="-1" aria-labelledby="CreateGroupFormLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded shadow border-0">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="LoginForm-title">Join Group</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body pt-0">

                <form action="javascript:;" onsubmit="return submitJoinGroupId();" id="joinGroupForm" class="needs-validation my-3" novalidate>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <div class="form-group d-flex">
                        <input name="join" data-group_id="{{ request.args.get('join') }}" id="join_group_id" class="form-control border-0 bg-light" placeholder="Join group" required="">
                        <button class="btn btn-primary submitBnt btn-pills" id="join_group_submit" disabled type="submit">Join</button>
                        <div class="invalid-feedback">
                            Please enter an id
                        </div>
                    </div>
                    <div class="small text-danger mt-1" id="joinGroupForm-feedback"></div>
                </form>
                {% if current_user.is_active %}
                <div class="col-lg-12 my-4 text-center">
                    <h6 class="text-muted">Or Create Group</h6>
                </div>

                <form action="{{url_for('groups.create')}}" method="POST" enctype="multipart/form-data" class="needs-validation row" novalidate>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

                    <div class="col-md-6">
                        <div class="mb-2">
                            <div class="form-group ">
                                <label for="join_group_new_name" class="form-label">
                                Name<span class="text-danger"> *</span>
                                </label>
                                <input id="join_group_new_name" class="form-control border-0 bg-light" minlength="3" maxlength="30" name="name" placeholder="Name" required="" type="text" value="">
                                <div class="invalid-feedback">
                                    Please enter a short name.
                                </div>

                            </div>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-md-6">
                        <div class="mb-2">
                            <div class="form-group">
                                <label for="privacy" class="form-label">
                                Privacy
                                </label>
                                <select id="privacy" name="privacy" class="form-select small border-0 bg-light">
                                    <option value="public" selected>Public</option>
                                    <option value="private">Private</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-md-12">
                        <div class="mb-2">
                            <label class="form-label">Description <span class="text-danger"> *</span></label>
                            <div class="form-icon position-relative">
                                <i data-feather="message-circle" class="fea icon-sm icons"></i>
                                <textarea name="description" id="validationCustomText" rows="2" maxlength="160" class="form-control ps-5 border-0 bg-light" placeholder="" required=""></textarea>
                                <div class="invalid-feedback">
                                    Please enter a short description.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-2">
                            <div class="form-group ">
                                <label for="location" class="form-label">
                                Location
                                </label>
                                <input id="location" class="form-control border-0 bg-light" name="location" placeholder="Location " maxlength="45" type="text" value="">
                            </div>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-md-12">
                        <div class="my-2">

                            <input type="submit" class="btn w-100 btn-primary searchbtn btn-pills" value="Create"/>
                        </div>
                    </div>

                </form>
                {% else %}
                <div class="col-lg-12 my-4 text-center">
                    <h6 class="text-muted">Or login to create one</h6>
                    <div class="text-center mt-4">
                        <a href="{{url_for('user.login')}}" class="btn me-2 btn-light searchbtn btn-pills">Login</a>
                        <a href="{{url_for('user.register')}}" class="btn ms-2 btn-secondary searchbtn btn-pills">Sign up</a>
                    </div>

                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>



{% endblock %}
{% block footer %}

<!-- abpoll js -->
<script src="/js/abpoll.js"></script>
{% endblock %}

abpoll/blueprints/groups/templates/groups/view.html
{% import 'macros/items.html' as items %}
{% import 'macros/sidebar.html' as sidebar %}
{% extends 'layouts/base-2.html' %}
{% block title %}{{group.name}} / ABpoll{% endblock %}
{% block description %}{{group.description}}{% endblock %}
{% block featured_image %}{{group.background or 'https://imagedelivery.net/hnHx9kxJyligwC1X9CPssg/2a3acbc2-d8af-4968-9417-4829c614f600/public'}}{% endblock %}
{% block header %}
<meta name="keywords" content="online voting, polls, society, likes, groups." />
<meta name="revisit-after" content="1 days">
{% endblock %}
{% block content %}
<div class="mt-4 d-block d-md-none">
    <!-- Spacer -->
</div>
<!-- Start -->
<section class="section">
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-xl-5 col-lg-6 col-md-7 col-sm-12 order-md-2 order-lg-2 order-1">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{category}} fade show m-0 mb-4">{{ message|safe }}</div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                <div class="card shadow rounded border-0 overflow-hidden">
                    <img src="{{group.background_profile() or 'https://imagedelivery.net/hnHx9kxJyligwC1X9CPssg/2a3acbc2-d8af-4968-9417-4829c614f600/public'}}" class="img-fluid" style="height: 200px;object-fit:cover;" alt="group's header image">
                    <div class="card-body d-flex align-items-center justify-content-between">
                        <div class="text-muted">
                            <div class="d-flex align-items-center">
                                <h5 class="mb-0 text-dark">{{group.name}}</h5>
                                <span class="badge rounded-md bg-info p ms-2">{{group.number_of_participants()}}<i class="uil uil-user"></i></span>
                            </div>
                            <p class="mb-0 mt-2">{{group.description}}</small>
                            {% if group.location %}
                            <p class="mt-2 mb-0 small"><span class="iconify fea icon-sm me-2" data-feather="map-pin" data-inline="false"></span> {{group.location }}</p>
                            {% endif %}
                        </div>
                        <a onclick='triggerShare({{ url_for('groups.view', group_id=group.id, _external=True) | tojson }}, {{group.name | tojson }}, {{group.description | tojson }})' class="btn text-muted m-0 p-0" title="Share this article">
                            <i class="uil uil-share-alt h5"></i>
                        </a>
                    </div>
                    {% if current_user.is_active and current_user == group.author%}
                    <a data-bs-target="#EditGroupForm" data-bs-toggle="modal" class="edit-group-button btn btn-light btn-icon position-absolute icon-sm rounded-circle" title="Edit this group">
                        <i class="uil uil-pen h5"></i>
                    </a>
                    {% endif %}

                </div>
                <div id="grid" class="row mt-4">
                    <div class="mt-4 d-block d-sm-none">
                        <!-- Spacer -->
                    </div>


                </div><!--end row-->



                <div id="loadMore" class="text-center mt-4">
                    <span class="h6 mb-0 cursor-pointer">Loading... <i class="mdi mdi-loading text-primary mdi-spin h4 mb-0 align-middle"></i></span>
                </div>
            </div>

            {{ sidebar.users() }}

        </div>
    </div>
</section>

{% if current_user.is_active and current_user == group.author%}

<!-- edit group modal start -->
<div class="modal fade" id="EditGroupForm" tabindex="-1" aria-labelledby="CreateGroupFormLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded shadow border-0">
            <div class="modal-header border-0">
                <h5 class="modal-title">Edit Group</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body pt-0">

                <form action="{{url_for('groups.edit')}}" method="POST" enctype="multipart/form-data" class="needs-validation row" novalidate>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input type="hidden" name="group_id" value="{{group.id}}">

                    <div class="col-md-12 mb-2">
                        <label class="form-label">Group header <small class="text-muted">(900 x 400 px)</small></label>
                        <div class="form-icon position-relative">
                            <input type="file" accept=".jpeg, .jpg, .jfif, .pjpeg, .pjp, .png, .gif" name="background" class="form-control ps-2">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="mb-2">
                            <div class="form-group ">
                                <label for="join_group_new_name" class="form-label">
                                Name<span class="text-danger"> *</span>
                                </label>
                                <input value="{{group.name}}" id="join_group_new_name" class="form-control border-0 bg-light" minlength="3" maxlength="30" name="name" placeholder="Name" required="" type="text">
                            </div>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-md-6">
                        <div class="mb-2">
                            <div class="form-group">
                                <label for="privacy" class="form-label">
                                Privacy
                                </label>
                                <select id="privacy" name="privacy" class="form-select small border-0 bg-light">
                                    <option value="public" {% if group.privacy == 'public' %}selected{% endif%}>Public</option>
                                    <option value="private"  {% if group.privacy == 'private' %}selected{% endif%}>Private</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-md-12">
                        <div class="mb-2">
                            <label class="form-label">Description <span class="text-danger"> *</span></label>
                            <div class="form-icon position-relative">
                                <i data-feather="message-circle" class="fea icon-sm icons"></i>
                                <textarea name="description" id="validationCustomText" rows="2" maxlength="160" class="form-control ps-5 border-0 bg-light" placeholder="" required="">{{group.description}}</textarea>
                                <div class="invalid-feedback">
                                    Please enter a short description.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-2">
                            <div class="form-group ">
                                <label for="location" class="form-label">
                                Location
                                </label>
                                <input id="location" class="form-control border-0 bg-light" name="location" placeholder="Location " maxlength="45" type="text" value="{{group.location or ''}}">
                            </div>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-md-12">
                        <div class="my-2 d-flex justify-content-between">
                            <a data-bs-target="#DeleteGroupForm" data-bs-toggle="modal" class="btn btn-icon text-muted"><i class="uil uil-trash"></i></a>
                            <input type="submit" class="btn  btn-primary searchbtn btn-pills" value="Save"/>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

<!-- edit group modal start -->
<div class="modal fade" id="DeleteGroupForm" tabindex="-1" aria-labelledby="DeleteGroupForm" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded shadow border-0">
            <div class="modal-body border-0">
                <h5 class="modal-title">Are you sure?</h5>
                <p>This group will be deleted and you will lose any changes and data related to it</p>
                <form action="{{url_for('groups.delete')}}" method="post" class="d-flex justify-content-between">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input type="hidden" name="group_id" value="{{group.id}}">

                    <button type="submit" class="btn btn-danger btn-pills">Yes</button>
                    <a class="btn btn-primary btn-pills btn-search" data-bs-dismiss="modal" aria-label="Close">No</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}
{% block footer %}
<!-- abpoll js -->
<script src="/js/infinite_scroll_group.js"></script>
<script src="/js/abpoll.js"></script>
{% endblock %}