abpoll/blueprints/admin/views.py
from flask import Blueprint, redirect, request, flash, url_for, render_template
from flask_login import login_required, current_user
from sqlalchemy import or_, text, func, and_, extract, desc

from abpoll.blueprints.predict.models import Event, Predict
from abpoll.blueprints.admin.models import Dashboard
from abpoll.blueprints.user.decorators import role_required
from abpoll.blueprints.billing.decorators import handle_stripe_exceptions
from abpoll.blueprints.billing.models.coupon import Coupon
from abpoll.blueprints.billing.models.subscription import Subscription
from abpoll.blueprints.post.models import Post, PostAVote, PostBVote, PostViewed, PostComment
from abpoll.blueprints.user.models import User
from abpoll.blueprints.message.models import PrivateChatMeta
from abpoll.blueprints.admin.forms import (
    SearchForm,
    BulkDeleteForm,
    UserForm,
    RefundForm,
    UserCancelSubscriptionForm,
    CouponForm,
)

from lib.util_datetime import convert_to_utc
from lib.util_json import render_json, parse_arg_from_requests
from lib.util_post import (
    random_post_id,
    return_cv2_image,
    create_array_from_argument,
    save_image_to_server,
    vertical_attach_images
)
from lib.upload_files import delete_image_from_cloudflare
from abpoll.extensions import db

import datetime
import collections

admin = Blueprint("admin", __name__, template_folder="templates")


@admin.before_request
@login_required
@role_required("admin")
def before_request():
    """ Protect all the admin endpoints. """
    pass


@admin.route("/admin/dashboard")
def dashboard():
    group_and_count_users = Dashboard.group_and_count_users()
    group_and_count_posts = Dashboard.group_and_count_posts()
    group_and_count_votes = Dashboard.group_and_count_votes()
    group_and_count_comments = Dashboard.group_and_count_comments()
    topics = Dashboard.topics()

    return render_template(
        "admin/dashboard.html",
        group_and_count_users=group_and_count_users,
        group_and_count_posts=group_and_count_posts,
        group_and_count_votes=group_and_count_votes,
        group_and_count_comments=group_and_count_comments,
        topics=topics,
    )


@admin.route("/admin/posts")
def posts_review():
    posts = Post.query.filter(Post.status != "immune").order_by(Post.created_on.desc())
    # posts = Post.query.order_by(Post.created_on.desc())
    return render_template("admin/posts-review.html", posts=posts)


@admin.route("/admin/posts/edit", methods=['POST'])
def edit_posts():
    post_id = request.values.get("post_id")
    post_to_edit = Post.query.get(post_id)

    if post_to_edit is not None:
        # New Title
        title = request.values.get("title", None)
        if title is not None or title != "":
            post_to_edit.title = title

        # Voting Mechanisms
        post_to_edit.a_text = request.values.get("a_text")
        post_to_edit.b_text = request.values.get("b_text")

        status = request.values.get("status", None)
        if status is not None:
            post_to_edit.status = status

        # Image 1
        image_1 = request.values.get("image_1_id")
        if image_1 != post_to_edit.image_1:
            # Delete Stored Image
            delete_image_from_cloudflare(post_to_edit.image_1)
            # Save the new image
            post_to_edit.image_1 = request.values.get("image_1_id")

        # Image 2
        image_2 = request.values.get("image_2_id")
        if image_2 is not None and image_2 != "":
            post_to_edit.image_2 = image_2
        else:
            post_to_edit.image_2 = None

        # Create tags
        post_to_edit.tags = create_array_from_argument(request.values.get("tags"))
        post_to_edit.accessibility = request.values.get("accessibility")

        post_to_edit.save()

    return redirect(request.referrer)


@admin.route("/admin/posts/approve", methods=['POST'])
def approve_posts():
    approved_post_id = parse_arg_from_requests("post_id")
    if approved_post_id is not None:
        approved_post = Post.query.get(approved_post_id)
        approved_post.status = "immune"
        approved_post.save()

        return render_json(200)
    return render_json(500)


@admin.route("/admin/users", defaults={"page": 1})
@admin.route("/admin/users/page/<int:page>")
def users(page):
    search_form = SearchForm()
    bulk_form = BulkDeleteForm()

    paginated_users = (
        User.query.filter(User.search(request.args.get("q", text("")))).order_by(User.updated_on.desc()).paginate(page,
                                                                                                                  50,
                                                                                                                  True)
    )

    return render_template(
        "admin/user-table.html",
        form=search_form,
        bulk_form=bulk_form,
        users=paginated_users,
    )


@admin.route("/admin/comments", defaults={"page": 1})
@admin.route("/admin/comments/page/<int:page>")
def comments_route(page):
    paginated_comments = PostComment.query.filter(PostComment.search(request.args.get("s", text("")))).order_by(
        PostComment.created_on.desc()).paginate(page, 50, True)

    return render_template(
        "admin/comments.html",
        comments=paginated_comments,
    )


@admin.route("/admin/users/edit", methods=['POST'])
def edit_user():
    user_id = request.values.get("user_id")
    user_to_edit = User.query.get(user_id)
    if user_to_edit.role == "admin":
        return redirect(url_for('admin.users'))

    if user_to_edit is not None:
        # New Title
        display_username = request.values.get("username")
        email = request.values.get("email").lower()

        if email is not None and user_to_edit.email != email:
            user_object = db.session.query(User).filter(User.email == email).first()
            if user_object is None:
                user_to_edit.email = email
                from abpoll.blueprints.user.tasks import email_confirmation

                email_confirmation(email, current_user.username)
                user_to_edit.email_verified = False
            else:
                flash("A user with this email already exists", "danger")
                return redirect(url_for('admin.users'))

        if display_username is not None and display_username != user_to_edit.display_username():
            username = str(display_username).lower()
            if current_user.username != username:
                user_object_username = db.session.query(User).filter(User.username == username).first()
                if user_object_username is not None:
                    flash(f"The username '{username}' is already taken.", "danger")
                    return redirect(url_for('admin.users'))
                else:
                    user_to_edit.username = username
                    user_to_edit.display_name = display_username

        # Voting Mechanisms
        user_to_edit.description = request.values.get("description")
        user_to_edit.status = request.values.get("user_status")
        location = request.values.get("location")
        user_to_edit.location = None

        if location != "" or location is None:
            user_to_edit.location = location

        # Image 1
        image_1 = request.values.get("image_1_id")
        if image_1 != user_to_edit.profile_picture:
            if user_to_edit.profile_picture is not None and "https:/" not in user_to_edit.profile_picture:
                delete_image_from_cloudflare(user_to_edit.profile_picture)
            user_to_edit.profile_picture = image_1

        social_1_option = request.values.get("social_1_option")
        social_1_handle = request.values.get("social_1_handle")

        if len(social_1_handle) <= 1:
            user_to_edit.social_1_handle = None
            user_to_edit.social_1_link = "#"
        else:
            if social_1_option == "Twitter":
                social_1 = social_1_handle.replace("@", "")
                social_1_link = f"https://twitter.com/{social_1}"
                user_to_edit.social_1_option = "twitter"
                user_to_edit.social_1_link = social_1_link
                user_to_edit.social_1_handle = social_1
            if social_1_option == "Instagram":
                social_1 = social_1_handle.replace("@", "")
                social_1_link = f"https://instagram.com/{social_1}"
                user_to_edit.social_1_option = "instagram"
                user_to_edit.social_1_link = social_1_link
                user_to_edit.social_1_handle = social_1
            if social_1_option == "Twitch":
                social_1 = social_1_handle.replace("@", "")
                social_1_link = f"https://twitch.tv/{social_1}"
                user_to_edit.social_1_option = "twitch"
                user_to_edit.social_1_link = social_1_link
                user_to_edit.social_1_handle = social_1
            if social_1_option == "Youtube":
                user_to_edit.social_1_option = "youtube"
                user_to_edit.social_1_link = social_1_handle
                user_to_edit.social_1_handle = "My Youtube"
            if social_1_option == "Website":
                web_link = f'https://{((social_1_handle.replace("www.", "")).replace("https://", "")).replace("http://", "")}'
                user_to_edit.social_1_option = "globe"
                user_to_edit.social_1_link = web_link
                user_to_edit.social_1_handle = "My Website"

        social_2_option = request.values.get("social_2_option")
        social_2_handle = request.values.get("social_2_handle")

        if len(social_2_handle) <= 1:
            user_to_edit.social_2_handle = None
            user_to_edit.social_2_link = "#"
        else:
            if social_2_option == "Twitter":
                social_2 = social_1_handle.replace("@", "")
                social_2_link = f"https://twitter.com/{social_2}"

abpoll/blueprints/general/views.py
from flask import (
    render_template,
    url_for,
    request,
    Blueprint,
    session,
)
from flask_login import current_user
from sqlalchemy import text, and_
from lib.util_json import render_json
import html

from abpoll.blueprints.post.models import Post, PostViewed

from abpoll.extensions import db
from abpoll.initializers import redis


general = Blueprint("general", __name__, template_folder="templates")
letters = 'abcdef'


@general.get("/up")
def up():
    redis.ping()
    db.engine.execute("SELECT 1")
    return ""


@general.route("/")
def home():
    # users to recommend

    return render_template("general/general-home.html")


@general.route("/infinite_scroll_api/page/<int:page>", methods=["POST"])
def infinite_scroll_api(page):
    posts = Post.recommend_random_posts()
    return render_json(200, [post.serialize for post in posts])


@general.route("/number_of_pages", methods=["POST"])
def number_of_pages():
    page = 1
    page_numbers = Post.query.filter(Post.status == "immune").order_by(Post.created_on.desc()).paginate(page, 2,
                                                                                                        True).pages
    return render_json(200, page_numbers)


@general.route("/explore", defaults={"page": 1})
@general.route("/explore/page/<int:page>")
def explore(page):
    search_query = request.args.get("s", text(""))
    products = Post.query.filter(Post.search(search_query)).paginate(page, 16, True)

    return render_template("general/general-explore.html", products=products)


@general.route("/terms")
def terms():
    return render_template("general/general-terms.html")


@general.route("/privacy")
def privacy():
    return render_template("general/general-privacy.html")


@general.route("/careers")
def careers():
    title = "careers page is coming soon as we expand the organisation at a steady pace"
    tags = "Careers in tech, coming soon, startup, social bid"
    description = (
        "If working for a startup is something you are looking forward to, "
        "stay tuned as we expand we will need a bigger and better team, follow us on twitter "
        '<a target="_blank" href="https://twitter.com/abpoll"  class="text-success">@abpoll</a> to receive updates.'
    )
    coming_soon = "Coming Soon..."
    return render_template(
        "errors/500.html",
        title=title,
        tags=tags,
        description=description,
        coming_soon=coming_soon,
    )

abpoll/templates/layouts/admin-settings.html
{% extends 'layouts/base.html' %}
{% block title %}Admin Dashboard / ABpoll{% endblock %}
{% block description %}Here you will be able to offer refunds, ban users, correct user's information, and get user insights.{% endblock %}
{% block header %}
<!-- simplebar -->
<link href="/css/simplebar.css" rel="stylesheet" type="text/css" />
<!-- Icons -->
<link href="/css/tabler-icons.min.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block page_bg %}bg-light{% endblock %}
{% block content %}
<div class="bg-half-40 bg-light"></div>
<div class="row bg-light">
    <!-- Side Nav START -->
    <div class="col-lg-3 col-md-4 col-12 d-lg-block d-none ">
        <div class="ps-4 sidebar sticky-bar ">
          <ul class="rounded list-unstyled sidebar-nav mb-0" id="navmenu-nav">
            <li class="navbar-item account-menu px-0 bg-white">
              <a
                class="navbar-link d-flex rounded shadow align-items-center py-2 px-4"
                href="javascript:void(0)"
              >
                <div class="text-start py-1 px-3">
                  <h6 class="mb-0 ms-2">
                    <i class="uil uil-dashboard h5 align-middle me-2 mb-0"></i>
                      Get ABpoll Plus
                  </h6>
                </div> </a><!--end nav link-->
            </li>
            <li class="navbar-item account-menu px-0 bg-white{% block not_dashboard %}{% endblock %}">
              <a
                class="navbar-link d-flex rounded shadow align-items-center py-2 px-4"
                href="{{url_for('admin.dashboard')}}"
              >
                <div class="text-start py-1 px-3">
                  <h6 class="mb-0 ms-2">
                    <i class="uil uil-dashboard h5 align-middle me-2 mb-0"></i>
                      Dashboard
                  </h6>
                </div> </a><!--end nav link-->
            </li>
            <!--end nav item-->

            <li class="navbar-item account-menu px-0 bg-white{% block product_analytics %}{% endblock %}">
              <a
                class="navbar-link d-flex rounded shadow align-items-center py-2 px-4"
                href="{{url_for('admin.posts')}}"
              >
                <div class="text-start py-1 px-3">
                  <h6 class="mb-0 ms-2">
                    <i class="uil uil-file-landscape-alt h5 align-middle me-2 mb-0"></i>
                    Posts Analytics
                  </h6>
                </div> </a><!--end nav link-->
            </li>
            <!--end nav item-->


            <li class="navbar-item account-menu px-0 bg-white{% block users_table %}{% endblock %}">
              <a
                class="navbar-link d-flex rounded shadow align-items-center py-2 px-4"
                href="{{url_for('admin.users')}}"
              >
                <div class="text-start py-1 px-3">
                  <h6 class="mb-0 ms-2">
                    <i class="uil uil-list-ul h5 align-middle me-2 mb-0"></i>
                    Users
                  </h6>
                </div>
              </a>
                <!--end nav link-->
            </li>
            <!--end nav item-->

            <li class="navbar-item account-menu px-0 bg-white{% block invoices_table %}{% endblock %}">
              <a
                class="navbar-link d-flex rounded shadow align-items-center py-2 px-4"
                id="account-details"
                href=""
              >
                <div class="text-start py-1 px-3">
                  <h6 class="mb-0 ms-2">
                    <i class="uil uil-transaction h5 align-middle me-2 mb-0"></i>
                      Invoices
                  </h6>
                </div>
              </a><!--end nav link-->
            </li>
            <!--end nav item-->
          </ul>
          <!--end nav pills-->
        </div>
    </div>
    <!-- Side Nav END -->

    <!-- Page Container START -->
    <div class="col-lg-9 col-12">
        <div class="page-container">
            {% block settings_field %}
            {% endblock %}
        </div>
    </div>
    {% block modal %}
    {% endblock %}
    <!-- Page Container END -->
</div>
{% endblock %}
{% block footer_bg %}bg-light{% endblock %}
{% block footer %}
<!-- simplebar -->
<script src="/js/simplebar.min.js"></script>
<!-- Chart -->
<script src="/js/apexcharts.min.js"></script>
{% endblock %}

abpoll/templates/layouts/anonymous-profile.html
{% extends 'layouts/base-2.html' %}
{% import 'macros/sidebar.html' as sidebar %}
{% block title %}Anonymous / ABpoll{% endblock %}
{% block description %}Here is the link of some of my preferences, to let you know more about me{% endblock %}
{% block featured_image %}https://imagedelivery.net/hnHx9kxJyligwC1X9CPssg/939d3f91-fa8b-4d78-fac6-4322c74b1b00/public{% endblock %}
{% block header %}
<meta name="revisit-after" content="1 days">
<script src="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.9.8/jQuery.tagify.min.js" integrity="sha512-/iKW064UdZxSuXUCuiLfwIcuzjQBM/OmCSsGfe7wJI72oQP1dsVTSkKmzYMurpXNJyNMFDiDBkpgZAbk4alUUA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.9.8/tagify.css" integrity="sha512-3TQTxe+kPDiA+h9hlIm4ydUdtreW8fVei75UUVmBioKA+prR2aYZqSDsCOBqGBmXJ4JSXKyj3bMHD1VAFDGyTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

{%endblock %}
{% block content %}
<!-- Start profile header -->
<section class="section">
    <div class="container mt-4-on-sm">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-8 col-sm-12 order-md-2 order-lg-2 order-1">
                <div class="card public-profile border-0 rounded">
                    <div class="card-body pb-0">
                        <div class="row align-items-center">
                            <div class="col-12">
                                <div class="text-center bg-white rounded">
                                    <img src="https://imagedelivery.net/hnHx9kxJyligwC1X9CPssg/32370b4d-eeb9-4bd3-3ce7-49ddfddd7d00/profile" class="rounded-circle shadow avatar avatar-md-md" alt="">
                                    <h5 class="mt-3">Anonymous</h5>
                                    <p class="text-muted">Here are some of my preferences and choices to let you know more about me.</p>

                                </div>
                            </div>
                        </div><!--end row-->


                        <a onclick='triggerShare("https://abpoll.com{{ url_for(request.endpoint, **request.view_args) }}", "Anonymous", "Here are some of my preferences and choices to let you know more about me.")' class="share-button btn position-absolute text-muted m-0 p-0" title="Share this article">
                            <i class="uil uil-share-alt h5"></i>
                        </a>

                    </div>
                </div>

                {% block post_content %}
                {% endblock %}

            </div><!--end col-->

            {{ sidebar.users() }}
        </div>
    </div>
</section>

<!-- End profile header -->

<div class="modal fade" id="ShareForm" tabindex="-1" aria-labelledby="EditFormLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded shadow border-0">
            <div class="modal-header border-0 px-4">
                <h5 class="modal-title">Share</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="shareon targets text-center" data-via="abpoll" data-title="Anonymous" data-text="Here are some of my preferences and choices to let you know more about me." data-url="https://abpoll.com{{ url_for(request.endpoint, **request.view_args) }}">
                <a class="btn btn-pills facebook">
                    <span>Facebook</span>
                </a>
                <a class="btn btn-pills twitter">
                    <span>Twitter</span>
                </a>
                <a class="btn btn-pills linkedin">
                    <span>LinkedIn</span>
                </a>
                <a class="btn btn-pills reddit">
                    <span>Reddit</span>
                </a>
            </div>
            <div class="share-link d-flex justify-content-between px-4">
                <div class="share-modal-url">https://abpoll.com{{ url_for(request.endpoint, **request.view_args) }}</div>
                <button onclick="copy_lick_to_clipboard()" class="copy-link btn btn-light searchbtn">Copy</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block footer %}
{% endblock %}

abpoll/templates/layouts/clean-payment.html
{% extends 'layouts/clean.html' %}
{% import 'macros/form.html' as f with context %}
{% import 'billing/macros/billing.html' as billing with context %}

{% block title %}Achieve more with ABpoll Plus{% endblock %}
{% block description %}ABpoll Plus has all the real time data you need to learn more about the world's needs. No survey necessary: simply sort..{% endblock %}
{% block header %}
<script src="https://js.stripe.com/v2/"></script>
<script type="module" src="/js/payments-app.js"></script>
<!-- Moment -->
{{ moment.include_moment() }}
{{ moment.locale(auto_detect=True) }}

{% endblock %}
{% block content %}
<div class="mt-4 d-block d-sm-none">
	<!-- Spacer -->
</div>
<section class="cover-user bg-white">
  <div class="container-fluid px-0">
      <div class="row g-0 position-relative">
          <div class="col-lg-6 padding-less img order-2 d-none d-lg-block" style="background-image: linear-gradient(300deg, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.7)), url(https://imagedelivery.net/hnHx9kxJyligwC1X9CPssg/cc9c3830-df27-4c0c-ea1d-887e1bdfbf00/public);" data-jarallax='{"speed": 0.5}'>
            <div class="m-4 px-4 text-white">
              <div class="py-4">
                <a class="logo " href="/">
                  <img src="/images/logo-light.png" height="36" class="logo-light-mode" alt="">
                </a> <i class="mdi mdi-crown text-gold"></i>  <span class="small">Plus</span>
              </div>
              <div class="mt-4">
                <h1>Achieve more with ABpoll Plus.</h2>
                <p>Your superpower for market research.</p>
              </div>
              <div class="mt-4">
                <ul class="list-unstyled">
                  <li class="mb-1"><span class="text-success h5 me-2"><i class="mdi mdi-check-circle align-middle"></i></span>15,000 responses already pre analyzed for you</li>
                  <li class="mb-1"><span class="text-success h5 me-2"><i class="mdi mdi-check-circle align-middle"></i></span>10 most popular survey topics pre created</li>
                  <li class="mb-1"><span class="text-success h5 me-2"><i class="mdi mdi-check-circle align-middle"></i></span>Access to similarity sorting and predictions</li>
                  <li class="mb-1"><span class="text-success h5 me-2"><i class="mdi mdi-check-circle align-middle"></i></span>Location sorting to learn more about your targeted location</li>
                </ul>
              </div>
            </div>

          </div><!-- end col -->

          <div class="col-lg-6 offset-lg-6 cover-my-30 order-1">
              <div class="cover-user-img d-flex align-items-center justify-content-center">
                  <div class="row">
                      <div class="col-12">
                          {% block inner_content %}
                          {% endblock %}
                      </div>
                      <!--end col-->
                  </div><!--end row-->
              </div> <!-- end about detail -->
          </div> <!-- end col -->
      </div><!--end row-->
  </div><!--end container fluid-->
</section><!--end section-->
{% endblock %}
{% block footer %}
        <script src="/js/payments.js"></script>
{% endblock %}

abpoll/templates/layouts/clean.html
<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta name="description" content="{% block description %}{% endblock %}" />
        <!-- Twitter SEO -->
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@abpoll" />
        <!-- Open Graph SEO -->
        <meta property="og:title" content="{{ self.title() }}" />
        <meta property="og:description" content="{{ self.description() }}" />
        <meta property="og:image" content="{% block featured_image %}{% endblock %}">
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="ABpoll">
        <!-- PWA -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="theme-color" content="#ffffff">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="is_logged_in" content="{% if current_user.is_active %} 1 {% else %} 0 {% endif %}">
        <meta name="is_user_registered" content="{% if not session['fingerprint_id'] %}{% if current_user.is_active and current_user.fingerprint_id == None %}0{% else %}1{% endif %}{% else %}1{% endif %}">
        <!-- favicon -->
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <!-- Web App Manifest -->
        <link rel="manifest" href="/manifest.json">
        <!--  disable cache -->
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="Expires" content="0">
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- Icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/6.5.95/css/materialdesignicons.min.css" integrity="sha512-Zw6ER2h5+Zjtrej6afEKgS8G5kehmDAHYp9M2xf38MPmpUWX39VrYmdGtCrDQbdLQrTnBVT8/gcNhgS4XPgvEg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@iconscout/unicons@3.0.6/css/line.css">
        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
        <!-- Main css -->
        <link href="/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="/css/clean.css" rel="stylesheet" type="text/css"/>
        <link href="/css/abpoll.css" rel="stylesheet" type="text/css">
        <link href="/css/colors/default.css" rel="stylesheet">
        <link href="/css/font/stylesheet.css" rel="stylesheet" type="text/css">

        <!-- Feather Icons    -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js" integrity="sha512-7x3zila4t2qNycrtZ31HO0NnJr8kg2VI67YLoRSyi9hGhRN66FHYWr7Axa9Y1J9tGYHVBPqIjSE1ogHrJTz51g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-264FH0BM28"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-264FH0BM28');
        </script>
        <!-- End Global site tag (gtag.js) - Google Analytics -->

        {% block header %}
        {% endblock %}

    </head>

    <body>
        <div class="back-to-home rounded">
            <a href="{{url_for('general.home')}}" class="btn btn-icon btn-soft-primary rounded-circle"><i data-feather="home" class="icons"></i></a>
        </div>
        <!-- start content -->
        {% block content %}
        {% endblock %}
        <!-- end content -->

        <!-- javascript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <!-- Lazy Load -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.11/jquery.lazy.min.js" integrity="sha512-eviLb3jW7+OaVLz5N3B5F0hpluwkLb8wTXHOTy0CyNaZM5IlShxX1nEbODak/C0k9UdsrWjqIBKOFY0ELCCArw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.11/jquery.lazy.plugins.js" integrity="sha512-+/Sdj6uywMdwvcdNCCbb4cSaiLiIz/tHyFr97ex++ynILaxFSW8u+fTMtJaTQza4BeU1RDMpWnh2Tl6XQVAjBA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- Main Js -->
        <script src="/js/plugins.init.js"></script><!--Note: All init js like tiny slider, counter, countdown, maintenance, lightbox, gallery, swiper slider, aos animation etc.-->
        <script src="/js/app.js"></script><!--Note: All important javascript like page loader, menu, sticky menu, menu-toggler, one page menu etc. -->
        {% block footer %}
        {% endblock %}
    </body>
</html>